AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: true
  Max: 320

Metrics/BlockLength:
  Enabled: true
  Max: 50

Metrics/MethodLength:
  Enabled: true
  Max: 50

Metrics/AbcSize:
  Enabled: true
  Max: 50

Style/SymbolProc:
  Enabled: false
